ARG ELIXIR_VERSION=1.14.2
ARG OTP_VERSION=25.2
ARG DEBIAN_VERSION=bullseye-20221004-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE}

USER nobody
COPY perm_error.exs /
COPY init.sh /

CMD ["/init.sh"]
